.\" Manpage for debug-container.
.\" Contact richard.steinbrueck@googlemail.com to correct errors or typos.
.TH man 1 "18 May 2021" "1.0" "debug man page"
.SH NAME
debug \- The DEBUG container for any moment in life
.SH DESCRIPTION
The DEBUG container for any moment in life
.SH Networking tools
dnsutils
iputils-clockdiff
iputils-arping
iputils-tracepath
iputils-ping

.SH HTTP clients
httpie
wget
curl

.SH Database clients
postgresql-client

.SH Loadtesting tools
hey
siege

.SH BUGS
No known bugs.
.SH AUTHOR
Richard Steinbrueck (richard.steinbrueck@googlemail.com)
